version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: multi-agent-postgres
    environment:
      POSTGRES_DB: multi_agent_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - multi-agent-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: multi-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - multi-agent-network

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: multi-agent-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/multi_agent_platform
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    networks:
      - multi-agent-network

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    container_name: multi-agent-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    networks:
      - multi-agent-network

volumes:
  postgres_data:
  redis_data:

networks:
  multi-agent-network:
    driver: bridge